[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E", "W",  # pycodestyle
    "F",  # Pyflakes
    "I",  # isort
    "N",  # pep8-naming
    "UP",  # pyupgrade
    "B",  # flake8-bugbear
    "A",  # flake8-builtins
    "PYI",  # flake8-pyi
    "Q",  # flake8-quotes
    "RET",  # flake8-return
    "SIM",  # flake8-simplify
    "ARG",  # flake8-unused-arguments
    "TD",  # flake8-todos
    "FIX",  # flake8-fixme
    "RUF",  # Ruff-specific rules
]

[tool.mypy]
strict = true
exclude = "Solutions/Day TEMPLATE/"
